version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: foodmysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: foodmenu-db
      MYSQL_USER: foodmenu
      MYSQL_PASSWORD: 123456
    ports:
      - "3388:3306"
    volumes:
      - mysql_food:/var/lib/mysql

volumes:
  mysql_food:
